extern ALLEGRO_PATH *al_create_path(const char *str);
extern ALLEGRO_PATH *al_create_path_for_directory(const char *str);
extern void al_destroy_path(ALLEGRO_PATH *path);
extern ALLEGRO_PATH *al_clone_path(const ALLEGRO_PATH *path);
extern bool al_join_paths(ALLEGRO_PATH *path, const ALLEGRO_PATH *tail);
extern bool al_rebase_path(const ALLEGRO_PATH *head, ALLEGRO_PATH *tail);
extern const char *al_get_path_drive(const ALLEGRO_PATH *path);
extern int al_get_path_num_components(const ALLEGRO_PATH *path);
extern const char *al_get_path_component(const ALLEGRO_PATH *path, int i);
extern const char *al_get_path_tail(const ALLEGRO_PATH *path);
extern const char *al_get_path_filename(const ALLEGRO_PATH *path);
extern const char *al_get_path_basename(const ALLEGRO_PATH *path);
extern const char *al_get_path_extension(const ALLEGRO_PATH *path);
extern void al_set_path_drive(ALLEGRO_PATH *path, const char *drive);
extern void al_append_path_component(ALLEGRO_PATH *path, const char *s);
extern void al_insert_path_component(ALLEGRO_PATH *path, int i, const char *s);
extern void al_replace_path_component(ALLEGRO_PATH *path, int i, const char *s);
extern void al_remove_path_component(ALLEGRO_PATH *path, int i);
extern void al_drop_path_tail(ALLEGRO_PATH *path);
extern void al_set_path_filename(ALLEGRO_PATH *path, const char *filename);
extern bool al_set_path_extension(ALLEGRO_PATH *path, char const *extension);
extern const char *al_path_cstr(const ALLEGRO_PATH *path, char delim);
extern bool al_make_path_canonical(ALLEGRO_PATH *path);
